name: onde_gastei_app
description: Aplicativo para registrar despesas pessoais.
publish_to: "none"

version: 1.2.0+16

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  # google_fonts: ^3.0.1
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.12.0
  flutter_dotenv: ^5.2.1
  firebase_remote_config: ^5.1.3
  logger: ^2.4.0
  # asuka: ^2.0.0+1
  # validatorless: ^1.2.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  grouped_list: ^6.0.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  firebase_performance: ^0.10.0+8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  hard_analyser: ^1.9.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  flutter_flavorizr: ^2.2.3

# dependency_overrides:
#   # Por causa do flutter_localizations
#   intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost-Black.ttf
          weight: 900
        - asset: fonts/Jost-Bold.ttf
          weight: 700
        - asset: fonts/Jost-Medium.ttf
          weight: 500
        - asset: fonts/Jost-Regular.ttf
          weight: 400
