name: onde_gastei_app
description: Aplicativo para registrar despesas pessoais.
publish_to: "none"

version: 1.1.1+10

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  # google_fonts: ^3.0.1
  flutter_screenutil: ">=5.9.0"
  dio: ^5.3.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter_dotenv: ^5.1.0
  firebase_remote_config: ^4.3.4
  logger: ^2.0.2+1
  # asuka: ^2.0.0+1
  # validatorless: ^1.2.1
  intl: ^0.18.1
  fl_chart: ^0.64.0
  grouped_list: ^5.1.2
  firebase_crashlytics: ^3.4.4
  firebase_analytics: ^10.7.0
  firebase_performance: ^0.9.3+4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.1
  hard_analyser: ^1.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  flutter_flavorizr: ^2.2.1

dependency_overrides:
  # Por causa do flutter_localizations
  intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost-Black.ttf
          weight: 900
        - asset: fonts/Jost-Bold.ttf
          weight: 700
        - asset: fonts/Jost-Medium.ttf
          weight: 500
        - asset: fonts/Jost-Regular.ttf
          weight: 400
