import 'package:flutter/material.dart';

class IconPicker {
  IconPicker._();

  static const List<IconData> icons = [
    Icons.abc,
    Icons.accessibility,
    Icons.accessibility_new,
    Icons.accessible,
    Icons.accessible_forward,
    Icons.account_balance,
    Icons.account_balance_wallet,
    Icons.account_box,
    Icons.account_circle,
    Icons.add_card,
    Icons.add_home,
    Icons.add_shopping_cart,
    Icons.add_task,
    Icons.add_to_drive,
    Icons.addchart,
    Icons.admin_panel_settings,
    Icons.ads_click,
    Icons.alarm,
    Icons.alarm_add,
    Icons.alarm_off,
    Icons.alarm_on,
    Icons.all_inbox,
    Icons.all_out,
    Icons.analytics,
    Icons.anchor,
    Icons.android,
    Icons.announcement,
    Icons.api,
    Icons.app_blocking,
    Icons.app_shortcut,
    Icons.arrow_circle_down,
    Icons.arrow_circle_left,
    Icons.arrow_circle_right,
    Icons.arrow_circle_up,
    Icons.arrow_right_alt,
    Icons.article,
    Icons.aspect_ratio,
    Icons.assessment,
    Icons.assignment,
    Icons.assignment_ind,
    Icons.assignment_late,
    Icons.assignment_return,
    Icons.assignment_returned,
    Icons.assignment_turned_in,
    Icons.assured_workload,
    Icons.autorenew,
    Icons.backup,
    Icons.backup_table,
    Icons.balance,
    Icons.batch_prediction,
    Icons.book,
    Icons.book_online,
    Icons.bookmark,
    Icons.bookmark_add,
    Icons.bookmark_added,
    Icons.bookmark_border,
    Icons.bookmark_remove,
    Icons.bookmarks,
    Icons.browse_gallery,
    Icons.bug_report,
    Icons.build,
    Icons.build_circle,
    Icons.cached,
    Icons.calendar_month,
    Icons.calendar_today,
    Icons.calendar_view_day,
    Icons.calendar_view_month,
    Icons.calendar_view_week,
    Icons.camera_enhance,
    Icons.cancel_schedule_send,
    Icons.card_giftcard,
    Icons.card_membership,
    Icons.card_travel,
    Icons.change_history,
    Icons.check_circle,
    Icons.check_circle_outline,
    Icons.chrome_reader_mode,
    Icons.circle_notifications,
    Icons.close_fullscreen,
    Icons.code,
    Icons.code_off,
    Icons.comment_bank,
    Icons.commit,
    Icons.commute,
    Icons.compare_arrows,
    Icons.compress,
    Icons.contact_page,
    Icons.contact_support,
    Icons.contactless,
    Icons.copyright,
    Icons.credit_card,
    Icons.credit_card_off,
    Icons.css,
    Icons.currency_exchange,
    Icons.dangerous,
    Icons.dashboard,
    Icons.dashboard_customize,
    Icons.data_exploration,
    Icons.data_thresholding,
    Icons.date_range,
    Icons.delete,
    Icons.delete_forever,
    Icons.delete_outline,
    Icons.density_large,
    Icons.density_medium,
    Icons.density_small,
    Icons.description,
    Icons.disabled_by_default,
    Icons.disabled_visible,
    Icons.display_settings,
    Icons.dns,
    Icons.done,
    Icons.done_all,
    Icons.done_outline,
    Icons.donut_large,
    Icons.donut_small,
    Icons.drag_indicator,
    Icons.dynamic_form,
    Icons.eco,
    Icons.edit_calendar,
    Icons.edit_off,
    Icons.eject,
    Icons.euro_symbol,
    Icons.event,
    Icons.event_repeat,
    Icons.event_seat,
    Icons.exit_to_app,
    Icons.expand,
    Icons.explore,
    Icons.explore_off,
    Icons.extension,
    Icons.extension_off,
    Icons.face,
    Icons.fact_check,
    Icons.favorite,
    Icons.favorite_border,
    Icons.fax,
    Icons.feedback,
    Icons.file_present,
    Icons.filter_alt,
    Icons.filter_alt_off,
    Icons.filter_list_alt,
    Icons.find_in_page,
    Icons.find_replace,
    Icons.fingerprint,
    Icons.fit_screen,
    Icons.flaky,
    Icons.flight_land,
    Icons.flight_takeoff,
    Icons.flip_to_back,
    Icons.flip_to_front,
    Icons.flutter_dash,
    Icons.free_cancellation,
    Icons.g_translate,
    Icons.gavel,
    Icons.generating_tokens,
    Icons.get_app,
    Icons.gif,
    Icons.gif_box,
    Icons.grade,
    Icons.grading,
    Icons.group_work,
    Icons.help,
    Icons.help_center,
    Icons.help_outline,
    Icons.hide_source,
    Icons.highlight_alt,
    Icons.highlight_off,
    Icons.history,
    Icons.history_toggle_off,
    Icons.hls,
    Icons.hls_off,
    Icons.home,
    Icons.home_filled,
    Icons.horizontal_split,
    Icons.hotel_class,
    Icons.hourglass_disabled,
    Icons.hourglass_empty,
    Icons.hourglass_full,
    Icons.html,
    Icons.http,
    Icons.https,
    Icons.important_devices,
    Icons.info,
    Icons.info_outline,
    Icons.input,
    Icons.install_desktop,
    Icons.install_mobile,
    Icons.integration_instructions,
    Icons.invert_colors,
    Icons.javascript,
    Icons.join_full,
    Icons.join_inner,
    Icons.join_left,
    Icons.join_right,
    Icons.label,
    Icons.label_important,
    Icons.label_important_outline,
    Icons.label_off,
    Icons.label_outline,
    Icons.language,
    Icons.launch,
    Icons.leaderboard,
    Icons.lightbulb,
    Icons.lightbulb_circle,
    Icons.lightbulb_outline,
    Icons.line_style,
    Icons.line_weight,
    Icons.list,
    Icons.lock,
    Icons.lock_clock,
    Icons.lock_open,
    Icons.lock_outline,
    Icons.lock_person,
    Icons.lock_reset,
    Icons.login,
    Icons.logout,
    Icons.loyalty,
    Icons.manage_accounts,
    Icons.manage_history,
    Icons.mark_as_unread,
    Icons.markunread_mailbox,
    Icons.maximize,
    Icons.mediation,
    Icons.minimize,
    Icons.model_training,
    Icons.network_ping,
    Icons.new_label,
    Icons.next_plan,
    Icons.nightlight_round,
    Icons.no_accounts,
    Icons.noise_aware,
    Icons.noise_control_off,
    Icons.not_accessible,
    Icons.not_started,
    Icons.note_add,
    Icons.offline_bolt,
    Icons.offline_pin,
    Icons.on_device_training,
    Icons.online_prediction,
    Icons.opacity,
    Icons.open_in_browser,
    Icons.open_in_full,
    Icons.open_in_new,
    Icons.open_in_new_off,
    Icons.open_with,
    Icons.outbond,
    Icons.outbound,
    Icons.outbox,
    Icons.outgoing_mail,
    Icons.outlet,
    Icons.output,
    Icons.pageview,
    Icons.paid,
    Icons.pan_tool,
    Icons.pan_tool_alt,
    Icons.payment,
    Icons.pending,
    Icons.pending_actions,
    Icons.percent,
    Icons.perm_camera_mic,
    Icons.perm_contact_calendar,
    Icons.perm_data_setting,
    Icons.perm_device_information,
    Icons.perm_identity,
    Icons.perm_media,
    Icons.perm_phone_msg,
    Icons.perm_scan_wifi,
    Icons.pets,
    Icons.php,
    Icons.picture_in_picture,
    Icons.picture_in_picture_alt,
    Icons.pin_end,
    Icons.pin_invoke,
    Icons.pinch,
    Icons.plagiarism,
    Icons.play_for_work,
    Icons.polymer,
    Icons.power_settings_new,
    Icons.pregnant_woman,
    Icons.preview,
    Icons.print,
    Icons.privacy_tip,
    Icons.private_connectivity,
    Icons.production_quantity_limits,
    Icons.published_with_changes,
    Icons.query_builder,
    Icons.question_answer,
    Icons.question_mark,
    Icons.quickreply,
    Icons.receipt,
    Icons.record_voice_over,
    Icons.redeem,
    Icons.remove_done,
    Icons.remove_shopping_cart,
    Icons.reorder,
    Icons.report_problem,
    Icons.request_page,
    Icons.restore,
    Icons.restore_from_trash,
    Icons.restore_page,
    Icons.rocket,
    Icons.rocket_launch,
    Icons.room,
    Icons.rounded_corner,
    Icons.rowing,
    Icons.rule,
    Icons.satellite_alt,
    Icons.saved_search,
    Icons.savings,
    Icons.schedule,
    Icons.schedule_send,
    Icons.search,
    Icons.search_off,
    Icons.segment,
    Icons.send_and_archive,
    Icons.sensors,
    Icons.sensors_off,
    Icons.settings,
    Icons.settings_accessibility,
    Icons.settings_applications,
    Icons.settings_backup_restore,
    Icons.settings_bluetooth,
    Icons.settings_brightness,
    Icons.settings_cell,
    Icons.settings_ethernet,
    Icons.settings_input_antenna,
    Icons.settings_input_component,
    Icons.settings_input_composite,
    Icons.settings_input_hdmi,
    Icons.settings_input_svideo,
    Icons.settings_overscan,
    Icons.settings_phone,
    Icons.settings_power,
    Icons.settings_remote,
    Icons.settings_voice,
    Icons.shop,
    Icons.shop_2,
    Icons.shop_two,
    Icons.shopping_bag,
    Icons.shopping_basket,
    Icons.shopping_cart,
    Icons.shopping_cart_checkout,
    Icons.smart_button,
    Icons.source,
    Icons.space_dashboard,
    Icons.spatial_audio,
    Icons.spatial_audio_off,
    Icons.spatial_tracking,
    Icons.speaker_notes,
    Icons.speaker_notes_off,
    Icons.spellcheck,
    Icons.star_rate,
    Icons.stars,
    Icons.sticky_note_2,
    Icons.store,
    Icons.subject,
    Icons.subtitles_off,
    Icons.supervised_user_circle,
    Icons.supervisor_account,
    Icons.support,
    Icons.swap_horiz,
    Icons.swap_horizontal_circle,
    Icons.swap_vert,
    Icons.swap_vertical_circle,
    Icons.swipe,
    Icons.swipe_down,
    Icons.swipe_down_alt,
    Icons.swipe_left,
    Icons.swipe_left_alt,
    Icons.swipe_right,
    Icons.swipe_right_alt,
    Icons.swipe_up,
    Icons.swipe_up_alt,
    Icons.swipe_vertical,
    Icons.switch_access_shortcut,
    Icons.switch_access_shortcut_add,
    Icons.sync_alt,
    Icons.system_update_alt,
    Icons.tab,
    Icons.tab_unselected,
    Icons.table_view,
    Icons.task_alt,
    Icons.terminal,
    Icons.text_rotate_up,
    Icons.text_rotate_vertical,
    Icons.text_rotation_angledown,
    Icons.text_rotation_angleup,
    Icons.text_rotation_down,
    Icons.text_rotation_none,
    Icons.theaters,
    Icons.thumb_down,
    Icons.thumb_down_off_alt,
    Icons.thumb_up,
    Icons.thumb_up_off_alt,
    Icons.thumbs_up_down,
    Icons.timeline,
    Icons.tips_and_updates,
    Icons.toc,
    Icons.today,
    Icons.token,
    Icons.toll,
    Icons.touch_app,
    Icons.tour,
    Icons.track_changes,
    Icons.transcribe,
    Icons.translate,
    Icons.trending_down,
    Icons.trending_flat,
    Icons.trending_up,
    Icons.troubleshoot,
    Icons.turned_in,
    Icons.turned_in_not,
    Icons.unpublished,
    Icons.update,
    Icons.update_disabled,
    Icons.upgrade,
    Icons.verified,
    Icons.verified_user,
    Icons.vertical_split,
    Icons.view_agenda,
    Icons.view_array,
    Icons.view_carousel,
    Icons.view_column,
    Icons.view_comfy_alt,
    Icons.view_compact_alt,
    Icons.view_cozy,
    Icons.view_day,
    Icons.view_headline,
    Icons.view_in_ar,
    Icons.view_kanban,
    Icons.view_list,
    Icons.view_module,
    Icons.view_quilt,
    Icons.view_sidebar,
    Icons.view_stream,
    Icons.view_timeline,
    Icons.view_week,
    Icons.visibility,
    Icons.visibility_off,
    Icons.voice_over_off,
    Icons.watch_later,
    Icons.webhook,
    Icons.width_full,
    Icons.width_normal,
    Icons.width_wide,
    Icons.wifi_protected_setup,
    Icons.work,
    Icons.work_history,
    Icons.work_off,
    Icons.work_outline,
    Icons.wysiwyg,
    Icons.youtube_searched_for,
    Icons.zoom_in,
    Icons.zoom_out,
    Icons.add_alert,
    Icons.auto_delete,
    Icons.error,
    Icons.error_outline,
    Icons.notification_important,
    Icons.warning,
    Icons.warning_amber,
    Icons.add_to_queue,
    Icons.airplay,
    Icons.album,
    Icons.art_track,
    Icons.audio_file,
    Icons.av_timer,
    Icons.branding_watermark,
    Icons.call_to_action,
    Icons.closed_caption,
    Icons.closed_caption_disabled,
    Icons.closed_caption_off,
    Icons.control_camera,
    Icons.equalizer,
    Icons.explicit,
    Icons.fast_forward,
    Icons.fast_rewind,
    Icons.featured_play_list,
    Icons.featured_video,
    Icons.fiber_dvr,
    Icons.fiber_manual_record,
    Icons.fiber_new,
    Icons.fiber_pin,
    Icons.fiber_smart_record,
    Icons.forward_10,
    Icons.forward_30,
    Icons.forward_5,
    Icons.games,
    Icons.hd,
    Icons.hearing,
    Icons.hearing_disabled,
    Icons.high_quality,
    Icons.interpreter_mode,
    Icons.library_add,
    Icons.library_add_check,
    Icons.library_books,
    Icons.library_music,
    Icons.loop,
    Icons.lyrics,
    Icons.mic,
    Icons.mic_none,
    Icons.mic_off,
    Icons.missed_video_call,
    Icons.movie,
    Icons.music_video,
    Icons.new_releases,
    Icons.not_interested,
    Icons.note,
    Icons.pause,
    Icons.pause_circle,
    Icons.pause_circle_filled,
    Icons.pause_circle_outline,
    Icons.play_arrow,
    Icons.play_circle,
    Icons.play_circle_filled,
    Icons.play_circle_outline,
    Icons.play_disabled,
    Icons.playlist_add,
    Icons.playlist_add_check,
    Icons.playlist_add_check_circle,
    Icons.playlist_add_circle,
    Icons.playlist_play,
    Icons.playlist_remove,
    Icons.queue,
    Icons.queue_music,
    Icons.queue_play_next,
    Icons.radio,
    Icons.recent_actors,
    Icons.remove_from_queue,
    Icons.repeat,
    Icons.repeat_on,
    Icons.repeat_one,
    Icons.repeat_one_on,
    Icons.replay,
    Icons.replay_10,
    Icons.replay_30,
    Icons.replay_5,
    Icons.replay_circle_filled,
    Icons.sd,
    Icons.shuffle,
    Icons.shuffle_on,
    Icons.skip_next,
    Icons.skip_previous,
    Icons.slow_motion_video,
    Icons.snooze,
    Icons.sort_by_alpha,
    Icons.speed,
    Icons.stop,
    Icons.stop_circle,
    Icons.subscriptions,
    Icons.subtitles,
    Icons.surround_sound,
    Icons.video_call,
    Icons.video_file,
    Icons.video_label,
    Icons.video_library,
    Icons.video_settings,
    Icons.videocam,
    Icons.videocam_off,
    Icons.volume_down,
    Icons.volume_down_alt,
    Icons.volume_mute,
    Icons.volume_off,
    Icons.volume_up,
    Icons.web,
    Icons.web_asset,
    Icons.web_asset_off,
    Icons.add_ic_call,
    Icons.alternate_email,
    Icons.app_registration,
    Icons.business,
    Icons.call,
    Icons.call_end,
    Icons.call_made,
    Icons.call_merge,
    Icons.call_missed,
    Icons.call_missed_outgoing,
    Icons.call_received,
    Icons.call_split,
    Icons.cancel_presentation,
    Icons.cell_tower,
    Icons.cell_wifi,
    Icons.chat,
    Icons.chat_bubble,
    Icons.chat_bubble_outline,
    Icons.clear_all,
    Icons.co_present,
    Icons.comment,
    Icons.comments_disabled,
    Icons.contact_mail,
    Icons.contact_phone,
    Icons.contacts,
    Icons.desktop_access_disabled,
    Icons.dialer_sip,
    Icons.dialpad,
    Icons.document_scanner,
    Icons.domain_disabled,
    Icons.domain_verification,
    Icons.duo,
    Icons.email,
    Icons.forum,
    Icons.forward_to_inbox,
    Icons.hourglass_bottom,
    Icons.hourglass_top,
    Icons.hub,
    Icons.import_contacts,
    Icons.import_export,
    Icons.invert_colors_off,
    Icons.key,
    Icons.key_off,
    Icons.list_alt,
    Icons.live_help,
    Icons.location_off,
    Icons.location_on,
    Icons.mail_lock,
    Icons.mail_outline,
    Icons.mark_chat_read,
    Icons.mark_chat_unread,
    Icons.mark_email_read,
    Icons.mark_email_unread,
    Icons.mark_unread_chat_alt,
    Icons.message,
    Icons.mobile_screen_share,
    Icons.more_time,
    Icons.nat,
    Icons.no_sim,
    Icons.pause_presentation,
    Icons.person_add_disabled,
    Icons.person_search,
    Icons.phone,
    Icons.phone_disabled,
    Icons.phone_enabled,
    Icons.phonelink_erase,
    Icons.phonelink_lock,
    Icons.phonelink_ring,
    Icons.phonelink_setup,
    Icons.portable_wifi_off,
    Icons.present_to_all,
    Icons.print_disabled,
    Icons.qr_code,
    Icons.qr_code_2,
    Icons.qr_code_scanner,
    Icons.read_more,
    Icons.ring_volume,
    Icons.rss_feed,
    Icons.rtt,
    Icons.screen_share,
    Icons.send_time_extension,
    Icons.sentiment_satisfied_alt,
    Icons.sip,
    Icons.speaker_phone,
    Icons.spoke,
    Icons.stay_current_landscape,
    Icons.stay_current_portrait,
    Icons.stay_primary_landscape,
    Icons.stay_primary_portrait,
    Icons.stop_screen_share,
    Icons.swap_calls,
    Icons.textsms,
    Icons.unsubscribe,
    Icons.voicemail,
    Icons.vpn_key,
    Icons.vpn_key_off,
    Icons.wifi_calling,
    Icons.add,
    Icons.add_box,
    Icons.add_circle,
    Icons.add_circle_outline,
    Icons.add_link,
    Icons.amp_stories,
    Icons.archive,
    Icons.attribution,
    Icons.backspace,
    Icons.ballot,
    Icons.biotech,
    Icons.block,
    Icons.block_flipped,
    Icons.bolt,
    Icons.calculate,
    Icons.change_circle,
    Icons.clear,
    Icons.content_copy,
    Icons.content_cut,
    Icons.content_paste,
    Icons.content_paste_go,
    Icons.content_paste_off,
    Icons.content_paste_search,
    Icons.copy_all,
    Icons.create,
    Icons.delete_sweep,
    Icons.deselect,
    Icons.drafts,
    Icons.dynamic_feed,
    Icons.file_copy,
    Icons.filter_list,
    Icons.filter_list_off,
    Icons.flag,
    Icons.flag_circle,
    Icons.font_download,
    Icons.font_download_off,
    Icons.forward,
    Icons.gesture,
    Icons.how_to_reg,
    Icons.how_to_vote,
    Icons.inbox,
    Icons.insights,
    Icons.inventory,
    Icons.inventory_2,
    Icons.link,
    Icons.link_off,
    Icons.low_priority,
    Icons.mail,
    Icons.markunread,
    Icons.move_to_inbox,
    Icons.next_week,
    Icons.outlined_flag,
    Icons.policy,
    Icons.push_pin,
    Icons.redo,
    Icons.remove,
    Icons.remove_circle,
    Icons.remove_circle_outline,
    Icons.reply,
    Icons.reply_all,
    Icons.report,
    Icons.report_gmailerrorred,
    Icons.report_off,
    Icons.save,
    Icons.save_alt,
    Icons.save_as,
    Icons.select_all,
    Icons.send,
    Icons.shield,
    Icons.sort,
    Icons.square_foot,
    Icons.stacked_bar_chart,
    Icons.stream,
    Icons.tag,
    Icons.text_format,
    Icons.unarchive,
    Icons.undo,
    Icons.upcoming,
    Icons.waves,
    Icons.web_stories,
    Icons.weekend,
    Icons.where_to_vote,
    Icons.access_alarm,
    Icons.access_alarms,
    Icons.access_time,
    Icons.access_time_filled,
    Icons.ad_units,
    Icons.add_alarm,
    Icons.add_to_home_screen,
    Icons.air,
    Icons.airplane_ticket,
    Icons.airplanemode_active,
    Icons.airplanemode_inactive,
    Icons.aod,
    Icons.battery_0_bar,
    Icons.battery_1_bar,
    Icons.battery_2_bar,
    Icons.battery_3_bar,
    Icons.battery_4_bar,
    Icons.battery_5_bar,
    Icons.battery_6_bar,
    Icons.battery_alert,
    Icons.battery_charging_full,
    Icons.battery_full,
    Icons.battery_saver,
    Icons.battery_std,
    Icons.battery_unknown,
    Icons.bloodtype,
    Icons.bluetooth,
    Icons.bluetooth_connected,
    Icons.bluetooth_disabled,
    Icons.bluetooth_drive,
    Icons.bluetooth_searching,
    Icons.brightness_auto,
    Icons.brightness_high,
    Icons.brightness_low,
    Icons.brightness_medium,
    Icons.cable,
    Icons.cameraswitch,
    Icons.credit_score,
    Icons.dark_mode,
    Icons.data_saver_off,
    Icons.data_saver_on,
    Icons.data_usage,
    Icons.dataset,
    Icons.dataset_linked,
    Icons.developer_mode,
    Icons.device_thermostat,
    Icons.devices,
    Icons.devices_fold,
    Icons.discount,
    Icons.do_not_disturb_on_total_silence,
    Icons.dvr,
    Icons.e_mobiledata,
    Icons.edgesensor_high,
    Icons.edgesensor_low,
    Icons.flashlight_off,
    Icons.flashlight_on,
    Icons.flourescent,
    Icons.fmd_bad,
    Icons.fmd_good,
    Icons.g_mobiledata,
    Icons.gpp_bad,
    Icons.gpp_good,
    Icons.gpp_maybe,
    Icons.gps_fixed,
    Icons.gps_not_fixed,
    Icons.gps_off,
    Icons.graphic_eq,
    Icons.grid_3x3,
    Icons.grid_4x4,
    Icons.grid_goldenratio,
    Icons.h_mobiledata,
    Icons.h_plus_mobiledata,
    Icons.hdr_auto,
    Icons.hdr_auto_select,
    Icons.hdr_off_select,
    Icons.hdr_on_select,
    Icons.lan,
    Icons.lens_blur,
    Icons.light_mode,
    Icons.location_disabled,
    Icons.location_searching,
    Icons.lte_mobiledata,
    Icons.lte_plus_mobiledata,
    Icons.media_bluetooth_off,
    Icons.media_bluetooth_on,
    Icons.medication,
    Icons.medication_liquid,
    Icons.mobile_friendly,
    Icons.mobile_off,
    Icons.mobiledata_off,
    Icons.mode_night,
    Icons.mode_standby,
    Icons.monitor_heart,
    Icons.monitor_weight,
    Icons.nearby_error,
    Icons.nearby_off,
    Icons.network_cell,
    Icons.network_wifi,
    Icons.network_wifi_1_bar,
    Icons.network_wifi_2_bar,
    Icons.network_wifi_3_bar,
    Icons.nfc,
    Icons.nightlight,
    Icons.note_alt,
    Icons.password,
    Icons.pattern,
    Icons.phishing,
    Icons.pin,
    Icons.play_lesson,
    Icons.price_change,
    Icons.price_check,
    Icons.punch_clock,
    Icons.quiz,
    Icons.r_mobiledata,
    Icons.radar,
    Icons.remember_me,
    Icons.reset_tv,
    Icons.restart_alt,
    Icons.reviews,
    Icons.rsvp,
    Icons.screen_lock_landscape,
    Icons.screen_lock_portrait,
    Icons.screen_lock_rotation,
    Icons.screen_rotation,
    Icons.screen_search_desktop,
    Icons.screenshot,
    Icons.screenshot_monitor,
    Icons.sd_storage,
    Icons.security_update,
    Icons.security_update_good,
    Icons.security_update_warning,
    Icons.sell,
    Icons.send_to_mobile,
    Icons.settings_suggest,
    Icons.settings_system_daydream,
    Icons.share_location,
    Icons.shortcut,
    Icons.signal_cellular_0_bar,
    Icons.signal_cellular_4_bar,
    Icons.signal_cellular_alt,
    Icons.signal_cellular_alt_1_bar,
    Icons.signal_cellular_alt_2_bar,
    Icons.signal_cellular_connected_no_internet_0_bar,
    Icons.signal_cellular_connected_no_internet_4_bar,
    Icons.signal_cellular_no_sim,
    Icons.signal_cellular_nodata,
    Icons.signal_cellular_null,
    Icons.signal_cellular_off,
    Icons.signal_wifi_0_bar,
    Icons.signal_wifi_4_bar,
    Icons.signal_wifi_4_bar_lock,
    Icons.signal_wifi_bad,
    Icons.signal_wifi_connected_no_internet_4,
    Icons.signal_wifi_off,
    Icons.signal_wifi_statusbar_4_bar,
    Icons.signal_wifi_statusbar_connected_no_internet_4,
    Icons.signal_wifi_statusbar_null,
    Icons.sim_card_download,
    Icons.splitscreen,
    Icons.sports_score,
    Icons.ssid_chart,
    Icons.storage,
    Icons.storm,
    Icons.summarize,
    Icons.system_security_update,
    Icons.system_security_update_good,
    Icons.system_security_update_warning,
    Icons.task,
    Icons.thermostat,
    Icons.timer_10_select,
    Icons.timer_3_select,
    Icons.tungsten,
    Icons.usb,
    Icons.usb_off,
    Icons.wallpaper,
    Icons.water,
    Icons.widgets,
    Icons.wifi_1_bar,
    Icons.wifi_2_bar,
    Icons.wifi_calling_3,
    Icons.wifi_channel,
    Icons.wifi_find,
    Icons.wifi_lock,
    Icons.wifi_password,
    Icons.wifi_tethering,
    Icons.wifi_tethering_error,
    Icons.wifi_tethering_error_rounded,
    Icons.wifi_tethering_off,
    Icons.add_chart,
    Icons.add_comment,
    Icons.align_horizontal_center,
    Icons.align_horizontal_left,
    Icons.align_horizontal_right,
    Icons.align_vertical_bottom,
    Icons.align_vertical_center,
    Icons.align_vertical_top,
    Icons.area_chart,
    Icons.attach_file,
    Icons.attach_money,
    Icons.auto_graph,
    Icons.bar_chart,
    Icons.border_all,
    Icons.border_bottom,
    Icons.border_clear,
    Icons.border_color,
    Icons.border_horizontal,
    Icons.border_inner,
    Icons.border_left,
    Icons.border_outer,
    Icons.border_right,
    Icons.border_style,
    Icons.border_top,
    Icons.border_vertical,
    Icons.bubble_chart,
    Icons.candlestick_chart,
    Icons.checklist,
    Icons.checklist_rtl,
    Icons.data_array,
    Icons.data_object,
    Icons.drag_handle,
    Icons.draw,
    Icons.edit_note,
    Icons.format_align_center,
    Icons.format_align_justify,
    Icons.format_align_left,
    Icons.format_align_right,
    Icons.format_bold,
    Icons.format_clear,
    Icons.format_color_fill,
    Icons.format_color_reset,
    Icons.format_color_text,
    Icons.format_indent_decrease,
    Icons.format_indent_increase,
    Icons.format_italic,
    Icons.format_line_spacing,
    Icons.format_list_bulleted,
    Icons.format_list_numbered,
    Icons.format_list_numbered_rtl,
    Icons.format_paint,
    Icons.format_quote,
    Icons.format_shapes,
    Icons.format_size,
    Icons.format_strikethrough,
    Icons.format_textdirection_l_to_r,
    Icons.format_textdirection_r_to_l,
    Icons.format_underlined,
    Icons.functions,
    Icons.height,
    Icons.hexagon,
    Icons.highlight,
    Icons.horizontal_distribute,
    Icons.horizontal_rule,
    Icons.insert_chart,
    Icons.insert_chart_outlined,
    Icons.insert_comment,
    Icons.insert_drive_file,
    Icons.insert_emoticon,
    Icons.insert_invitation,
    Icons.insert_link,
    Icons.insert_page_break,
    Icons.insert_photo,
    Icons.line_axis,
    Icons.linear_scale,
    Icons.margin,
    Icons.merge_type,
    Icons.mode,
    Icons.mode_comment,
    Icons.mode_edit,
    Icons.mode_edit_outline,
    Icons.monetization_on,
    Icons.money_off,
    Icons.money_off_csred,
    Icons.move_down,
    Icons.move_up,
    Icons.multiline_chart,
    Icons.notes,
    Icons.numbers,
    Icons.padding,
    Icons.pentagon,
    Icons.pie_chart,
    Icons.pie_chart_outline,
    Icons.polyline,
    Icons.post_add,
    Icons.publish,
    Icons.query_stats,
    Icons.rectangle,
    Icons.scatter_plot,
    Icons.schema,
    Icons.score,
    Icons.short_text,
    Icons.show_chart,
    Icons.space_bar,
    Icons.square,
    Icons.stacked_line_chart,
    Icons.strikethrough_s,
    Icons.subscript,
    Icons.superscript,
    Icons.table_chart,
    Icons.table_rows,
    Icons.text_decrease,
    Icons.text_fields,
    Icons.text_increase,
    Icons.title,
    Icons.type_specimen,
    Icons.vertical_align_bottom,
    Icons.vertical_align_center,
    Icons.vertical_align_top,
    Icons.vertical_distribute,
    Icons.wrap_text,
    Icons.approval,
    Icons.attach_email,
    Icons.attachment,
    Icons.cloud,
    Icons.cloud_circle,
    Icons.cloud_done,
    Icons.cloud_download,
    Icons.cloud_off,
    Icons.cloud_queue,
    Icons.cloud_sync,
    Icons.cloud_upload,
    Icons.create_new_folder,
    Icons.difference,
    Icons.download,
    Icons.download_done,
    Icons.download_for_offline,
    Icons.downloading,
    Icons.drive_file_move,
    Icons.drive_file_move_outline,
    Icons.drive_file_move_rtl,
    Icons.drive_file_rename_outline,
    Icons.drive_folder_upload,
    Icons.file_download,
    Icons.file_download_done,
    Icons.file_download_off,
    Icons.file_open,
    Icons.file_upload,
    Icons.folder,
    Icons.folder_copy,
    Icons.folder_delete,
    Icons.folder_off,
    Icons.folder_open,
    Icons.folder_shared,
    Icons.folder_zip,
    Icons.format_overline,
    Icons.grid_view,
    Icons.newspaper,
    Icons.request_quote,
    Icons.rule_folder,
    Icons.snippet_folder,
    Icons.text_snippet,
    Icons.topic,
    Icons.upload,
    Icons.upload_file,
    Icons.workspaces,
    Icons.workspaces_filled,
    Icons.workspaces_outline,
    Icons.adf_scanner,
    Icons.browser_not_supported,
    Icons.browser_updated,
    Icons.cast,
    Icons.cast_connected,
    Icons.cast_for_education,
    Icons.computer,
    Icons.connected_tv,
    Icons.desktop_mac,
    Icons.desktop_windows,
    Icons.developer_board,
    Icons.developer_board_off,
    Icons.device_hub,
    Icons.device_unknown,
    Icons.devices_other,
    Icons.dock,
    Icons.earbuds,
    Icons.earbuds_battery,
    Icons.gamepad,
    Icons.headphones,
    Icons.headphones_battery,
    Icons.headset,
    Icons.headset_mic,
    Icons.headset_off,
    Icons.home_max,
    Icons.home_mini,
    Icons.keyboard,
    Icons.keyboard_alt,
    Icons.keyboard_arrow_down,
    Icons.keyboard_arrow_left,
    Icons.keyboard_arrow_right,
    Icons.keyboard_arrow_up,
    Icons.keyboard_backspace,
    Icons.keyboard_capslock,
    Icons.keyboard_command_key,
    Icons.keyboard_control_key,
    Icons.keyboard_double_arrow_down,
    Icons.keyboard_double_arrow_left,
    Icons.keyboard_double_arrow_right,
    Icons.keyboard_double_arrow_up,
    Icons.keyboard_hide,
    Icons.keyboard_option_key,
    Icons.keyboard_return,
    Icons.keyboard_tab,
    Icons.keyboard_voice,
    Icons.laptop,
    Icons.laptop_chromebook,
    Icons.laptop_mac,
    Icons.laptop_windows,
    Icons.memory,
    Icons.monitor,
    Icons.mouse,
    Icons.phone_android,
    Icons.phone_iphone,
    Icons.phonelink,
    Icons.phonelink_off,
    Icons.point_of_sale,
    Icons.power_input,
    Icons.router,
    Icons.scanner,
    Icons.security,
    Icons.sim_card,
    Icons.smart_display,
    Icons.smart_screen,
    Icons.smart_toy,
    Icons.smartphone,
    Icons.speaker,
    Icons.speaker_group,
    Icons.start,
    Icons.tablet,
    Icons.tablet_android,
    Icons.tablet_mac,
    Icons.toys,
    Icons.tv,
    Icons.videogame_asset,
    Icons.videogame_asset_off,
    Icons.watch,
    Icons.watch_off,
    Icons.auto_mode,
    Icons.blinds,
    Icons.blinds_closed,
    Icons.broadcast_on_home,
    Icons.broadcast_on_personal,
    Icons.cloudy_snowing,
    Icons.curtains,
    Icons.curtains_closed,
    Icons.electric_bolt,
    Icons.electric_meter,
    Icons.energy_savings_leaf,
    Icons.foggy,
    Icons.gas_meter,
    Icons.heat_pump,
    Icons.mode_fan_off,
    Icons.nest_cam_wired_stand,
    Icons.oil_barrel,
    Icons.propane,
    Icons.propane_tank,
    Icons.roller_shades,
    Icons.roller_shades_closed,
    Icons.sensor_door,
    Icons.sensor_occupied,
    Icons.sensor_window,
    Icons.shield_moon,
    Icons.snowing,
    Icons.solar_power,
    Icons.sunny,
    Icons.sunny_snowing,
    Icons.vertical_shades,
    Icons.vertical_shades_closed,
    Icons.wind_power,
    Icons.add_a_photo,
    Icons.add_photo_alternate,
    Icons.add_to_photos,
    Icons.adjust,
    Icons.animation,
    Icons.assistant,
    Icons.assistant_photo,
    Icons.audiotrack,
    Icons.auto_awesome,
    Icons.auto_awesome_mosaic,
    Icons.auto_awesome_motion,
    Icons.auto_fix_high,
    Icons.auto_fix_normal,
    Icons.auto_fix_off,
    Icons.auto_stories,
    Icons.autofps_select,
    Icons.bedtime,
    Icons.bedtime_off,
    Icons.blur_circular,
    Icons.blur_linear,
    Icons.blur_off,
    Icons.blur_on,
    Icons.brightness_1,
    Icons.brightness_2,
    Icons.brightness_3,
    Icons.brightness_4,
    Icons.brightness_5,
    Icons.brightness_6,
    Icons.brightness_7,
    Icons.broken_image,
    Icons.brush,
    Icons.burst_mode,
    Icons.camera,
    Icons.camera_alt,
    Icons.camera_front,
    Icons.camera_rear,
    Icons.camera_roll,
    Icons.cases,
    Icons.center_focus_strong,
    Icons.center_focus_weak,
    Icons.circle,
    Icons.collections,
    Icons.collections_bookmark,
    Icons.color_lens,
    Icons.colorize,
    Icons.compare,
    Icons.contrast,
    Icons.control_point,
    Icons.control_point_duplicate,
    Icons.crop,
    Icons.crop_16_9,
    Icons.crop_3_2,
    Icons.crop_5_4,
    Icons.crop_7_5,
    Icons.crop_din,
    Icons.crop_free,
    Icons.crop_landscape,
    Icons.crop_original,
    Icons.crop_portrait,
    Icons.crop_rotate,
    Icons.crop_square,
    Icons.currency_bitcoin,
    Icons.currency_franc,
    Icons.currency_lira,
    Icons.currency_pound,
    Icons.currency_ruble,
    Icons.currency_rupee,
    Icons.currency_yen,
    Icons.currency_yuan,
    Icons.deblur,
    Icons.dehaze,
    Icons.details,
    Icons.dirty_lens,
    Icons.edit,
    Icons.euro,
    Icons.exposure,
    Icons.exposure_neg_1,
    Icons.exposure_neg_2,
    Icons.exposure_plus_1,
    Icons.exposure_plus_2,
    Icons.exposure_zero,
    Icons.face_retouching_natural,
    Icons.face_retouching_off,
    Icons.filter,
    Icons.filter_1,
    Icons.filter_2,
    Icons.filter_3,
    Icons.filter_4,
    Icons.filter_5,
    Icons.filter_6,
    Icons.filter_7,
    Icons.filter_8,
    Icons.filter_9,
    Icons.filter_9_plus,
    Icons.filter_b_and_w,
    Icons.filter_center_focus,
    Icons.filter_drama,
    Icons.filter_frames,
    Icons.filter_hdr,
    Icons.filter_none,
    Icons.filter_tilt_shift,
    Icons.filter_vintage,
    Icons.flare,
    Icons.flash_auto,
    Icons.flash_off,
    Icons.flash_on,
    Icons.flip,
    Icons.flip_camera_android,
    Icons.flip_camera_ios,
    Icons.gradient,
    Icons.grain,
    Icons.grid_off,
    Icons.grid_on,
    Icons.hdr_enhanced_select,
    Icons.hdr_off,
    Icons.hdr_on,
    Icons.hdr_plus,
    Icons.hdr_strong,
    Icons.hdr_weak,
    Icons.healing,
    Icons.hevc,
    Icons.hide_image,
    Icons.image,
    Icons.image_aspect_ratio,
    Icons.image_not_supported,
    Icons.image_search,
    Icons.incomplete_circle,
    Icons.iso,
    Icons.landscape,
    Icons.leak_add,
    Icons.leak_remove,
    Icons.lens,
    Icons.linked_camera,
    Icons.logo_dev,
    Icons.looks,
    Icons.looks_3,
    Icons.looks_4,
    Icons.looks_5,
    Icons.looks_6,
    Icons.looks_one,
    Icons.looks_two,
    Icons.loupe,
    Icons.mic_external_off,
    Icons.mic_external_on,
    Icons.monochrome_photos,
    Icons.motion_photos_auto,
    Icons.motion_photos_off,
    Icons.motion_photos_on,
    Icons.motion_photos_pause,
    Icons.motion_photos_paused,
    Icons.movie_creation,
    Icons.movie_filter,
    Icons.mp,
    Icons.music_note,
    Icons.music_off,
    Icons.nature,
    Icons.nature_people,
    Icons.navigate_before,
    Icons.navigate_next,
    Icons.palette,
    Icons.panorama,
    Icons.panorama_fish_eye,
    Icons.panorama_horizontal,
    Icons.panorama_horizontal_select,
    Icons.panorama_photosphere,
    Icons.panorama_photosphere_select,
    Icons.panorama_vertical,
    Icons.panorama_vertical_select,
    Icons.panorama_wide_angle,
    Icons.panorama_wide_angle_select,
    Icons.photo,
    Icons.photo_album,
    Icons.photo_camera,
    Icons.photo_camera_back,
    Icons.photo_camera_front,
    Icons.photo_filter,
    Icons.photo_library,
    Icons.photo_size_select_actual,
    Icons.photo_size_select_large,
    Icons.photo_size_select_small,
    Icons.picture_as_pdf,
    Icons.portrait,
    Icons.raw_off,
    Icons.raw_on,
    Icons.receipt_long,
    Icons.remove_red_eye,
    Icons.rotate_90_degrees_ccw,
    Icons.rotate_90_degrees_cw,
    Icons.rotate_left,
    Icons.rotate_right,
    Icons.shutter_speed,
    Icons.slideshow,
    Icons.straighten,
    Icons.style,
    Icons.switch_camera,
    Icons.switch_video,
    Icons.tag_faces,
    Icons.texture,
    Icons.thermostat_auto,
    Icons.timelapse,
    Icons.timer,
    Icons.timer_10,
    Icons.timer_3,
    Icons.timer_off,
    Icons.tonality,
    Icons.transform,
    Icons.tune,
    Icons.video_camera_back,
    Icons.video_camera_front,
    Icons.video_stable,
    Icons.view_comfy,
    Icons.view_compact,
    Icons.vignette,
    Icons.vrpano,
    Icons.wb_auto,
    Icons.wb_cloudy,
    Icons.wb_incandescent,
    Icons.wb_iridescent,
    Icons.wb_shade,
    Icons.wb_sunny,
    Icons.wb_twighlight,
    Icons.wb_twilight,
    Icons.add_business,
    Icons.add_location,
    Icons.add_location_alt,
    Icons.add_road,
    Icons.agriculture,
    Icons.airline_stops,
    Icons.airlines,
    Icons.alt_route,
    Icons.atm,
    Icons.attractions,
    Icons.badge,
    Icons.bakery_dining,
    Icons.beenhere,
    Icons.bike_scooter,
    Icons.breakfast_dining,
    Icons.brunch_dining,
    Icons.bus_alert,
    Icons.car_crash,
    Icons.car_rental,
    Icons.car_repair,
    Icons.castle,
    Icons.category,
    Icons.celebration,
    Icons.church,
    Icons.cleaning_services,
    Icons.compass_calibration,
    Icons.connecting_airports,
    Icons.crisis_alert,
    Icons.delivery_dining,
    Icons.departure_board,
    Icons.design_services,
    Icons.diamond,
    Icons.dinner_dining,
    Icons.directions,
    Icons.directions_bike,
    Icons.directions_boat,
    Icons.directions_boat_filled,
    Icons.directions_bus,
    Icons.directions_bus_filled,
    Icons.directions_car,
    Icons.directions_car_filled,
    Icons.directions_railway,
    Icons.directions_railway_filled,
    Icons.directions_run,
    Icons.directions_subway,
    Icons.directions_subway_filled,
    Icons.directions_transit,
    Icons.directions_transit_filled,
    Icons.directions_walk,
    Icons.dry_cleaning,
    Icons.edit_attributes,
    Icons.edit_location,
    Icons.edit_location_alt,
    Icons.edit_road,
    Icons.egg,
    Icons.egg_alt,
    Icons.electric_bike,
    Icons.electric_car,
    Icons.electric_moped,
    Icons.electric_rickshaw,
    Icons.electric_scooter,
    Icons.electrical_services,
    Icons.emergency,
    Icons.emergency_recording,
    Icons.emergency_share,
    Icons.ev_station,
    Icons.factory,
    Icons.fastfood,
    Icons.festival,
    Icons.fire_hydrant_alt,
    Icons.fire_truck,
    Icons.flight,
    Icons.flight_class,
    Icons.forest,
    Icons.fork_left,
    Icons.fork_right,
    Icons.fort,
    Icons.hail,
    Icons.handyman,
    Icons.hardware,
    Icons.home_repair_service,
    Icons.hotel,
    Icons.hvac,
    Icons.icecream,
    Icons.kebab_dining,
    Icons.layers,
    Icons.layers_clear,
    Icons.liquor,
    Icons.local_activity,
    Icons.local_airport,
    Icons.local_atm,
    Icons.local_bar,
    Icons.local_cafe,
    Icons.local_car_wash,
    Icons.local_convenience_store,
    Icons.local_dining,
    Icons.local_drink,
    Icons.local_fire_department,
    Icons.local_florist,
    Icons.local_gas_station,
    Icons.local_grocery_store,
    Icons.local_hospital,
    Icons.local_hotel,
    Icons.local_laundry_service,
    Icons.local_library,
    Icons.local_mall,
    Icons.local_movies,
    Icons.local_offer,
    Icons.local_parking,
    Icons.local_pharmacy,
    Icons.local_phone,
    Icons.local_pizza,
    Icons.local_play,
    Icons.local_police,
    Icons.local_post_office,
    Icons.local_printshop,
    Icons.local_see,
    Icons.local_shipping,
    Icons.local_taxi,
    Icons.location_pin,
    Icons.lunch_dining,
    Icons.map,
    Icons.maps_ugc,
    Icons.medical_information,
    Icons.medical_services,
    Icons.menu_book,
    Icons.merge,
    Icons.minor_crash,
    Icons.miscellaneous_services,
    Icons.mode_of_travel,
    Icons.money,
    Icons.moped,
    Icons.mosque,
    Icons.moving,
    Icons.multiple_stop,
    Icons.museum,
    Icons.my_location,
    Icons.navigation,
    Icons.near_me,
    Icons.near_me_disabled,
    Icons.nightlife,
    Icons.no_crash,
    Icons.no_meals,
    Icons.no_meals_ouline,
    Icons.no_transfer,
    Icons.not_listed_location,
    Icons.park,
    Icons.pedal_bike,
    Icons.person_pin,
    Icons.person_pin_circle,
    Icons.pest_control,
    Icons.pest_control_rodent,
    Icons.pin_drop,
    Icons.place,
    Icons.plumbing,
    Icons.railway_alert,
    Icons.ramen_dining,
    Icons.ramp_left,
    Icons.ramp_right,
    Icons.rate_review,
    Icons.remove_road,
    Icons.restaurant,
    Icons.restaurant_menu,
    Icons.roundabout_left,
    Icons.roundabout_right,
    Icons.route,
    Icons.run_circle,
    Icons.safety_check,
    Icons.sailing,
    Icons.satellite,
    Icons.screen_rotation_alt,
    Icons.set_meal,
    Icons.signpost,
    Icons.snowmobile,
    Icons.sos,
    Icons.soup_kitchen,
    Icons.stadium,
    Icons.store_mall_directory,
    Icons.straight,
    Icons.streetview,
    Icons.subway,
    Icons.synagogue,
    Icons.takeout_dining,
    Icons.taxi_alert,
    Icons.temple_buddhist,
    Icons.temple_hindu,
    Icons.terrain,
    Icons.theater_comedy,
    Icons.tire_repair,
    Icons.traffic,
    Icons.train,
    Icons.tram,
    Icons.transfer_within_a_station,
    Icons.transit_enterexit,
    Icons.trip_origin,
    Icons.turn_left,
    Icons.turn_right,
    Icons.turn_sharp_left,
    Icons.turn_sharp_right,
    Icons.turn_slight_left,
    Icons.turn_slight_right,
    Icons.two_wheeler,
    Icons.u_turn_left,
    Icons.u_turn_right,
    Icons.volunteer_activism,
    Icons.warehouse,
    Icons.wine_bar,
    Icons.wrong_location,
    Icons.zoom_in_map,
    Icons.zoom_out_map,
    Icons.add_home_work,
    Icons.app_settings_alt,
    Icons.apps,
    Icons.apps_outage,
    Icons.arrow_back,
    Icons.arrow_back_ios,
    Icons.arrow_back_ios_new,
    Icons.arrow_downward,
    Icons.arrow_drop_down,
    Icons.arrow_drop_down_circle,
    Icons.arrow_drop_up,
    Icons.arrow_forward,
    Icons.arrow_forward_ios,
    Icons.arrow_left,
    Icons.arrow_right,
    Icons.arrow_upward,
    Icons.assistant_direction,
    Icons.assistant_navigation,
    Icons.campaign,
    Icons.cancel,
    Icons.check,
    Icons.chevron_left,
    Icons.chevron_right,
    Icons.close,
    Icons.double_arrow,
    Icons.east,
    Icons.expand_circle_down,
    Icons.expand_less,
    Icons.expand_more,
    Icons.first_page,
    Icons.fullscreen,
    Icons.fullscreen_exit,
    Icons.home_work,
    Icons.last_page,
    Icons.legend_toggle,
    Icons.maps_home_work,
    Icons.menu,
    Icons.menu_open,
    Icons.more_horiz,
    Icons.more_vert,
    Icons.north,
    Icons.north_east,
    Icons.north_west,
    Icons.offline_share,
    Icons.payments,
    Icons.pivot_table_chart,
    Icons.refresh,
    Icons.south,
    Icons.south_east,
    Icons.south_west,
    Icons.subdirectory_arrow_left,
    Icons.subdirectory_arrow_right,
    Icons.switch_left,
    Icons.switch_right,
    Icons.unfold_less,
    Icons.unfold_more,
    Icons.waterfall_chart,
    Icons.west,
    Icons.account_tree,
    Icons.adb,
    Icons.add_call,
    Icons.airline_seat_flat,
    Icons.airline_seat_flat_angled,
    Icons.airline_seat_individual_suite,
    Icons.airline_seat_legroom_extra,
    Icons.airline_seat_legroom_normal,
    Icons.airline_seat_legroom_reduced,
    Icons.airline_seat_recline_extra,
    Icons.airline_seat_recline_normal,
    Icons.bluetooth_audio,
    Icons.confirmation_number,
    Icons.directions_off,
    Icons.disc_full,
    Icons.do_disturb,
    Icons.do_disturb_alt,
    Icons.do_disturb_off,
    Icons.do_disturb_on,
    Icons.do_not_disturb,
    Icons.do_not_disturb_alt,
    Icons.do_not_disturb_off,
    Icons.do_not_disturb_on,
    Icons.drive_eta,
    Icons.enhanced_encryption,
    Icons.event_available,
    Icons.event_busy,
    Icons.event_note,
    Icons.folder_special,
    Icons.imagesearch_roller,
    Icons.live_tv,
    Icons.mms,
    Icons.more,
    Icons.network_check,
    Icons.network_locked,
    Icons.no_encryption,
    Icons.no_encryption_gmailerrorred,
    Icons.ondemand_video,
    Icons.personal_video,
    Icons.phone_bluetooth_speaker,
    Icons.phone_callback,
    Icons.phone_forwarded,
    Icons.phone_in_talk,
    Icons.phone_locked,
    Icons.phone_missed,
    Icons.phone_paused,
    Icons.power,
    Icons.power_off,
    Icons.priority_high,
    Icons.running_with_errors,
    Icons.sd_card,
    Icons.sd_card_alert,
    Icons.sim_card_alert,
    Icons.sms,
    Icons.sms_failed,
    Icons.support_agent,
    Icons.sync,
    Icons.sync_disabled,
    Icons.sync_lock,
    Icons.sync_problem,
    Icons.system_update,
    Icons.tap_and_play,
    Icons.time_to_leave,
    Icons.tv_off,
    Icons.vibration,
    Icons.voice_chat,
    Icons.vpn_lock,
    Icons.wc,
    Icons.wifi,
    Icons.wifi_off,
    Icons.ac_unit,
    Icons.airport_shuttle,
    Icons.all_inclusive,
    Icons.apartment,
    Icons.baby_changing_station,
    Icons.backpack,
    Icons.balcony,
    Icons.bathtub,
    Icons.beach_access,
    Icons.bento,
    Icons.bungalow,
    Icons.business_center,
    Icons.cabin,
    Icons.carpenter,
    Icons.casino,
    Icons.chalet,
    Icons.charging_station,
    Icons.checkroom,
    Icons.child_care,
    Icons.child_friendly,
    Icons.corporate_fare,
    Icons.cottage,
    Icons.countertops,
    Icons.crib,
    Icons.desk,
    Icons.do_not_step,
    Icons.do_not_touch,
    Icons.dry,
    Icons.elevator,
    Icons.escalator,
    Icons.escalator_warning,
    Icons.family_restroom,
    Icons.fence,
    Icons.fire_extinguisher,
    Icons.fitness_center,
    Icons.food_bank,
    Icons.foundation,
    Icons.free_breakfast,
    Icons.gite,
    Icons.golf_course,
    Icons.grass,
    Icons.holiday_village,
    Icons.hot_tub,
    Icons.house,
    Icons.house_siding,
    Icons.houseboat,
    Icons.iron,
    Icons.kitchen,
    Icons.meeting_room,
    Icons.microwave,
    Icons.night_shelter,
    Icons.no_backpack,
    Icons.no_cell,
    Icons.no_drinks,
    Icons.no_flash,
    Icons.no_food,
    Icons.no_meeting_room,
    Icons.no_photography,
    Icons.no_stroller,
    Icons.other_houses,
    Icons.pool,
    Icons.rice_bowl,
    Icons.roofing,
    Icons.room_preferences,
    Icons.room_service,
    Icons.rv_hookup,
    Icons.smoke_free,
    Icons.smoking_rooms,
    Icons.soap,
    Icons.spa,
    Icons.sports_bar,
    Icons.stairs,
    Icons.storefront,
    Icons.stroller,
    Icons.tapas,
    Icons.tty,
    Icons.umbrella,
    Icons.vape_free,
    Icons.vaping_rooms,
    Icons.villa,
    Icons.wash,
    Icons.water_damage,
    Icons.wheelchair_pickup,
    Icons.bathroom,
    Icons.bed,
    Icons.bedroom_baby,
    Icons.bedroom_child,
    Icons.bedroom_parent,
    Icons.blender,
    Icons.camera_indoor,
    Icons.camera_outdoor,
    Icons.chair,
    Icons.chair_alt,
    Icons.coffee,
    Icons.coffee_maker,
    Icons.dining,
    Icons.door_sliding,
    Icons.doorbell,
    Icons.feed,
    Icons.flatware,
    Icons.garage,
    Icons.light,
    Icons.living,
    Icons.manage_search,
    Icons.podcasts,
    Icons.shower,
    Icons.table_bar,
    Icons.table_restaurant,
    Icons.window,
    Icons.yard,
    Icons.add_moderator,
    Icons.add_reaction,
    Icons.architecture,
    Icons.back_hand,
    Icons.boy,
    Icons.cake,
    Icons.catching_pokemon,
    Icons.clean_hands,
    Icons.co2,
    Icons.compost,
    Icons.connect_without_contact,
    Icons.construction,
    Icons.cookie,
    Icons.coronavirus,
    Icons.cruelty_free,
    Icons.cyclone,
    Icons.deck,
    Icons.domain,
    Icons.domain_add,
    Icons.downhill_skiing,
    Icons.edit_notifications,
    Icons.elderly,
    Icons.elderly_woman,
    Icons.emoji_emotions,
    Icons.emoji_events,
    Icons.emoji_flags,
    Icons.emoji_food_beverage,
    Icons.emoji_nature,
    Icons.emoji_objects,
    Icons.emoji_people,
    Icons.emoji_symbols,
    Icons.emoji_transportation,
    Icons.engineering,
    Icons.facebook,
    Icons.female,
    Icons.fireplace,
    Icons.fitbit,
    Icons.flood,
    Icons.follow_the_signs,
    Icons.front_hand,
    Icons.girl,
    Icons.group,
    Icons.group_add,
    Icons.group_off,
    Icons.group_remove,
    Icons.groups,
    Icons.handshake,
    Icons.health_and_safety,
    Icons.heart_broken,
    Icons.hiking,
    Icons.history_edu,
    Icons.hive,
    Icons.ice_skating,
    Icons.interests,
    Icons.ios_share,
    Icons.kayaking,
    Icons.king_bed,
    Icons.kitesurfing,
    Icons.landslide,
    Icons.location_city,
    Icons.luggage,
    Icons.male,
    Icons.man,
    Icons.masks,
    Icons.military_tech,
    Icons.mood,
    Icons.mood_bad,
    Icons.nights_stay,
    Icons.no_adult_content,
    Icons.no_luggage,
    Icons.nordic_walking,
    Icons.notification_add,
    Icons.notifications,
    Icons.notifications_active,
    Icons.notifications_none,
    Icons.notifications_off,
    Icons.notifications_paused,
    Icons.outdoor_grill,
    Icons.pages,
    Icons.paragliding,
    Icons.party_mode,
    Icons.people,
    Icons.people_alt,
    Icons.people_outline,
    Icons.person,
    Icons.person_add,
    Icons.person_add_alt,
    Icons.person_add_alt_1,
    Icons.person_off,
    Icons.person_outline,
    Icons.person_remove,
    Icons.person_remove_alt_1,
    Icons.personal_injury,
    Icons.piano,
    Icons.piano_off,
    Icons.pix,
    Icons.plus_one,
    Icons.poll,
    Icons.precision_manufacturing,
    Icons.psychology,
    Icons.public,
    Icons.public_off,
    Icons.real_estate_agent,
    Icons.recommend,
    Icons.recycling,
    Icons.reduce_capacity,
    Icons.remove_moderator,
    Icons.roller_skating,
    Icons.safety_divider,
    Icons.sanitizer,
    Icons.scale,
    Icons.school,
    Icons.science,
    Icons.scoreboard,
    Icons.scuba_diving,
    Icons.self_improvement,
    Icons.sentiment_dissatisfied,
    Icons.sentiment_neutral,
    Icons.sentiment_satisfied,
    Icons.sentiment_very_dissatisfied,
    Icons.sentiment_very_satisfied,
    Icons.severe_cold,
    Icons.share,
    Icons.sick,
    Icons.sign_language,
    Icons.single_bed,
    Icons.skateboarding,
    Icons.sledding,
    Icons.snowboarding,
    Icons.snowshoeing,
    Icons.social_distance,
    Icons.south_america,
    Icons.sports,
    Icons.sports_baseball,
    Icons.sports_basketball,
    Icons.sports_cricket,
    Icons.sports_esports,
    Icons.sports_football,
    Icons.sports_golf,
    Icons.sports_gymnastics,
    Icons.sports_handball,
    Icons.sports_hockey,
    Icons.sports_kabaddi,
    Icons.sports_martial_arts,
    Icons.sports_mma,
    Icons.sports_motorsports,
    Icons.sports_rugby,
    Icons.sports_soccer,
    Icons.sports_tennis,
    Icons.sports_volleyball,
    Icons.surfing,
    Icons.switch_account,
    Icons.thumb_down_alt,
    Icons.thumb_up_alt,
    Icons.thunderstorm,
    Icons.tornado,
    Icons.transgender,
    Icons.travel_explore,
    Icons.tsunami,
    Icons.vaccines,
    Icons.volcano,
    Icons.wallet,
    Icons.water_drop,
    Icons.waving_hand,
    // Icons.whatsapp,
    Icons.whatshot,
    Icons.woman,
    Icons.workspace_premium,
    Icons.check_box,
    Icons.check_box_outline_blank,
    Icons.indeterminate_check_box,
    Icons.radio_button_checked,
    Icons.radio_button_unchecked,
    Icons.star,
    Icons.star_border,
    Icons.star_border_purple500,
    Icons.star_half,
    Icons.star_outline,
    Icons.star_purple500,
    Icons.toggle_off,
    Icons.toggle_on,
  ];

  // static const List<IconData> icons = [
  //   Icons.threesixty,
  //   Icons.threed_rotation,
  //   Icons.four_k,
  //   Icons.ac_unit,
  //   Icons.access_alarm,
  //   Icons.access_alarms,
  //   Icons.access_time,
  //   Icons.accessibility,
  //   Icons.accessibility_new,
  //   Icons.accessible,
  //   Icons.accessible_forward,
  //   Icons.account_balance,
  //   Icons.account_balance_wallet,
  //   Icons.account_box,
  //   Icons.account_circle,
  //   Icons.adb,
  //   Icons.add,
  //   Icons.add_a_photo,
  //   Icons.add_alarm,
  //   Icons.add_alert,
  //   Icons.add_box,
  //   Icons.add_call,
  //   Icons.add_circle,
  //   Icons.add_circle_outline,
  //   Icons.add_comment,
  //   Icons.add_location,
  //   Icons.add_photo_alternate,
  //   Icons.add_shopping_cart,
  //   Icons.add_to_home_screen,
  //   Icons.add_to_photos,
  //   Icons.add_to_queue,
  //   Icons.adjust,
  //   Icons.airline_seat_flat,
  //   Icons.airline_seat_flat_angled,
  //   Icons.airline_seat_individual_suite,
  //   Icons.airline_seat_legroom_extra,
  //   Icons.airline_seat_legroom_normal,
  //   Icons.airline_seat_legroom_reduced,
  //   Icons.airline_seat_recline_extra,
  //   Icons.airline_seat_recline_normal,
  //   Icons.airplanemode_active,
  //   Icons.airplanemode_inactive,
  //   Icons.airplay,
  //   Icons.airport_shuttle,
  //   Icons.alarm,
  //   Icons.alarm_add,
  //   Icons.alarm_off,
  //   Icons.alarm_on,
  //   Icons.album,
  //   Icons.all_inclusive,
  //   Icons.all_out,
  //   Icons.alternate_email,
  //   Icons.android,
  //   Icons.announcement,
  //   Icons.apps,
  //   Icons.archive,
  //   Icons.arrow_back,
  //   Icons.arrow_back_ios,
  //   Icons.arrow_downward,
  //   Icons.arrow_drop_down,
  //   Icons.arrow_drop_down_circle,
  //   Icons.arrow_drop_up,
  //   Icons.arrow_forward,
  //   Icons.arrow_forward_ios,
  //   Icons.arrow_left,
  //   Icons.arrow_right,
  //   Icons.arrow_upward,
  //   Icons.art_track,
  //   Icons.aspect_ratio,
  //   Icons.assessment,
  //   Icons.assignment,
  //   Icons.assignment_ind,
  //   Icons.assignment_late,
  //   Icons.assignment_return,
  //   Icons.assignment_returned,
  //   Icons.assignment_turned_in,
  //   Icons.assistant,
  //   Icons.assistant_photo,
  //   Icons.atm,
  //   Icons.attach_file,
  //   Icons.attach_money,
  //   Icons.attachment,
  //   Icons.audiotrack,
  //   Icons.autorenew,
  //   Icons.av_timer,
  //   Icons.backspace,
  //   Icons.backup,
  //   Icons.battery_alert,
  //   Icons.battery_charging_full,
  //   Icons.battery_full,
  //   Icons.battery_std,
  //   Icons.battery_unknown,
  //   Icons.beach_access,
  //   Icons.beenhere,
  //   Icons.block,
  //   Icons.bluetooth,
  //   Icons.bluetooth_audio,
  //   Icons.bluetooth_connected,
  //   Icons.bluetooth_disabled,
  //   Icons.bluetooth_searching,
  //   Icons.blur_circular,
  //   Icons.blur_linear,
  //   Icons.blur_off,
  //   Icons.blur_on,
  //   Icons.book,
  //   Icons.bookmark,
  //   Icons.bookmark_border,
  //   Icons.border_all,
  //   Icons.border_bottom,
  //   Icons.border_clear,
  //   Icons.border_color,
  //   Icons.border_horizontal,
  //   Icons.border_inner,
  //   Icons.border_left,
  //   Icons.border_outer,
  //   Icons.border_right,
  //   Icons.border_style,
  //   Icons.border_top,
  //   Icons.border_vertical,
  //   Icons.branding_watermark,
  //   Icons.brightness_1,
  //   Icons.brightness_2,
  //   Icons.brightness_3,
  //   Icons.brightness_4,
  //   Icons.brightness_5,
  //   Icons.brightness_6,
  //   Icons.brightness_7,
  //   Icons.brightness_auto,
  //   Icons.brightness_high,
  //   Icons.brightness_low,
  //   Icons.brightness_medium,
  //   Icons.broken_image,
  //   Icons.brush,
  //   Icons.bubble_chart,
  //   Icons.bug_report,
  //   Icons.build,
  //   Icons.burst_mode,
  //   Icons.business,
  //   Icons.business_center,
  //   Icons.cached,
  //   Icons.cake,
  //   Icons.calendar_today,
  //   Icons.calendar_view_day,
  //   Icons.call,
  //   Icons.call_end,
  //   Icons.call_made,
  //   Icons.call_merge,
  //   Icons.call_missed,
  //   Icons.call_missed_outgoing,
  //   Icons.call_received,
  //   Icons.call_split,
  //   Icons.call_to_action,
  //   Icons.camera,
  //   Icons.camera_alt,
  //   Icons.camera_enhance,
  //   Icons.camera_front,
  //   Icons.camera_rear,
  //   Icons.camera_roll,
  //   Icons.cancel,
  //   Icons.card_giftcard,
  //   Icons.card_membership,
  //   Icons.card_travel,
  //   Icons.casino,
  //   Icons.cast,
  //   Icons.cast_connected,
  //   Icons.category,
  //   Icons.center_focus_strong,
  //   Icons.center_focus_weak,
  //   Icons.change_history,
  //   Icons.chat,
  //   Icons.chat_bubble,
  //   Icons.chat_bubble_outline,
  //   Icons.check,
  //   Icons.check_box,
  //   Icons.check_box_outline_blank,
  //   Icons.check_circle,
  //   Icons.check_circle_outline,
  //   Icons.chevron_left,
  //   Icons.chevron_right,
  //   Icons.child_care,
  //   Icons.child_friendly,
  //   Icons.chrome_reader_mode,
  //   Icons.class_,
  //   Icons.clear,
  //   Icons.clear_all,
  //   Icons.close,
  //   Icons.closed_caption,
  //   Icons.cloud,
  //   Icons.cloud_circle,
  //   Icons.cloud_done,
  //   Icons.cloud_download,
  //   Icons.cloud_off,
  //   Icons.cloud_queue,
  //   Icons.cloud_upload,
  //   Icons.code,
  //   Icons.collections,
  //   Icons.collections_bookmark,
  //   Icons.color_lens,
  //   Icons.colorize,
  //   Icons.comment,
  //   Icons.compare,
  //   Icons.compare_arrows,
  //   Icons.computer,
  //   Icons.confirmation_number,
  //   Icons.contact_mail,
  //   Icons.contact_phone,
  //   Icons.contacts,
  //   Icons.content_copy,
  //   Icons.content_cut,
  //   Icons.content_paste,
  //   Icons.control_point,
  //   Icons.control_point_duplicate,
  //   Icons.copyright,
  //   Icons.create,
  //   Icons.create_new_folder,
  //   Icons.credit_card,
  //   Icons.crop,
  //   Icons.crop_16_9,
  //   Icons.crop_3_2,
  //   Icons.crop_5_4,
  //   Icons.crop_7_5,
  //   Icons.crop_din,
  //   Icons.crop_free,
  //   Icons.crop_landscape,
  //   Icons.crop_original,
  //   Icons.crop_portrait,
  //   Icons.crop_rotate,
  //   Icons.crop_square,
  //   Icons.dashboard,
  //   Icons.data_usage,
  //   Icons.date_range,
  //   Icons.dehaze,
  //   Icons.delete,
  //   Icons.delete_forever,
  //   Icons.delete_outline,
  //   Icons.delete_sweep,
  //   Icons.departure_board,
  //   Icons.description,
  //   Icons.desktop_mac,
  //   Icons.desktop_windows,
  //   Icons.details,
  //   Icons.developer_board,
  //   Icons.developer_mode,
  //   Icons.device_hub,
  //   Icons.device_unknown,
  //   Icons.devices,
  //   Icons.devices_other,
  //   Icons.dialer_sip,
  //   Icons.dialpad,
  //   Icons.directions,
  //   Icons.directions_bike,
  //   Icons.directions_boat,
  //   Icons.directions_bus,
  //   Icons.directions_car,
  //   Icons.directions_railway,
  //   Icons.directions_run,
  //   Icons.directions_subway,
  //   Icons.directions_transit,
  //   Icons.directions_walk,
  //   Icons.disc_full,
  //   Icons.dns,
  //   Icons.do_not_disturb,
  //   Icons.do_not_disturb_alt,
  //   Icons.do_not_disturb_off,
  //   Icons.do_not_disturb_on,
  //   Icons.dock,
  //   Icons.domain,
  //   Icons.done,
  //   Icons.done_all,
  //   Icons.done_outline,
  //   Icons.donut_large,
  //   Icons.donut_small,
  //   Icons.drafts,
  //   Icons.drag_handle,
  //   Icons.drive_eta,
  //   Icons.dvr,
  //   Icons.edit,
  //   Icons.edit_attributes,
  //   Icons.edit_location,
  //   Icons.eject,
  //   Icons.email,
  //   Icons.enhanced_encryption,
  //   Icons.equalizer,
  //   Icons.error,
  //   Icons.error_outline,
  //   Icons.euro_symbol,
  //   Icons.ev_station,
  //   Icons.event,
  //   Icons.event_available,
  //   Icons.event_busy,
  //   Icons.event_note,
  //   Icons.event_seat,
  //   Icons.exit_to_app,
  //   Icons.expand_less,
  //   Icons.expand_more,
  //   Icons.explicit,
  //   Icons.explore,
  //   Icons.exposure,
  //   Icons.exposure_neg_1,
  //   Icons.exposure_neg_2,
  //   Icons.exposure_plus_1,
  //   Icons.exposure_plus_2,
  //   Icons.exposure_zero,
  //   Icons.extension,
  //   Icons.face,
  //   Icons.fast_forward,
  //   Icons.fast_rewind,
  //   Icons.fastfood,
  //   Icons.favorite,
  //   Icons.favorite_border,
  //   Icons.featured_play_list,
  //   Icons.featured_video,
  //   Icons.feedback,
  //   Icons.fiber_dvr,
  //   Icons.fiber_manual_record,
  //   Icons.fiber_new,
  //   Icons.fiber_pin,
  //   Icons.fiber_smart_record,
  //   Icons.file_download,
  //   Icons.file_upload,
  //   Icons.filter,
  //   Icons.filter_1,
  //   Icons.filter_2,
  //   Icons.filter_3,
  //   Icons.filter_4,
  //   Icons.filter_5,
  //   Icons.filter_6,
  //   Icons.filter_7,
  //   Icons.filter_8,
  //   Icons.filter_9,
  //   Icons.filter_9_plus,
  //   Icons.filter_b_and_w,
  //   Icons.filter_center_focus,
  //   Icons.filter_drama,
  //   Icons.filter_frames,
  //   Icons.filter_hdr,
  //   Icons.filter_list,
  //   Icons.filter_none,
  //   Icons.filter_tilt_shift,
  //   Icons.filter_vintage,
  //   Icons.find_in_page,
  //   Icons.find_replace,
  //   Icons.fingerprint,
  //   Icons.first_page,
  //   Icons.fitness_center,
  //   Icons.flag,
  //   Icons.flare,
  //   Icons.flash_auto,
  //   Icons.flash_off,
  //   Icons.flash_on,
  //   Icons.flight,
  //   Icons.flight_land,
  //   Icons.flight_takeoff,
  //   Icons.flip,
  //   Icons.flip_to_back,
  //   Icons.flip_to_front,
  //   Icons.folder,
  //   Icons.folder_open,
  //   Icons.folder_shared,
  //   Icons.folder_special,
  //   Icons.font_download,
  //   Icons.format_align_center,
  //   Icons.format_align_justify,
  //   Icons.format_align_left,
  //   Icons.format_align_right,
  //   Icons.format_bold,
  //   Icons.format_clear,
  //   Icons.format_color_fill,
  //   Icons.format_color_reset,
  //   Icons.format_color_text,
  //   Icons.format_indent_decrease,
  //   Icons.format_indent_increase,
  //   Icons.format_italic,
  //   Icons.format_line_spacing,
  //   Icons.format_list_bulleted,
  //   Icons.format_list_numbered,
  //   Icons.format_list_numbered_rtl,
  //   Icons.format_paint,
  //   Icons.format_quote,
  //   Icons.format_shapes,
  //   Icons.format_size,
  //   Icons.format_strikethrough,
  //   Icons.format_textdirection_l_to_r,
  //   Icons.format_textdirection_r_to_l,
  //   Icons.format_underlined,
  //   Icons.forum,
  //   Icons.forward,
  //   Icons.forward_10,
  //   Icons.forward_30,
  //   Icons.forward_5,
  //   Icons.free_breakfast,
  //   Icons.fullscreen,
  //   Icons.fullscreen_exit,
  //   Icons.functions,
  //   Icons.g_translate,
  //   Icons.gamepad,
  //   Icons.games,
  //   Icons.gavel,
  //   Icons.gesture,
  //   Icons.get_app,
  //   Icons.gif,
  //   Icons.golf_course,
  //   Icons.gps_fixed,
  //   Icons.gps_not_fixed,
  //   Icons.gps_off,
  //   Icons.grade,
  //   Icons.gradient,
  //   Icons.grain,
  //   Icons.graphic_eq,
  //   Icons.grid_off,
  //   Icons.grid_on,
  //   Icons.group,
  //   Icons.group_add,
  //   Icons.group_work,
  //   Icons.hd,
  //   Icons.hdr_off,
  //   Icons.hdr_on,
  //   Icons.hdr_strong,
  //   Icons.hdr_weak,
  //   Icons.headset,
  //   Icons.headset_mic,
  //   Icons.headset_off,
  //   Icons.healing,
  //   Icons.hearing,
  //   Icons.help,
  //   Icons.help_outline,
  //   Icons.high_quality,
  //   Icons.highlight,
  //   Icons.highlight_off,
  //   Icons.history,
  //   Icons.home,
  //   Icons.hot_tub,
  //   Icons.hotel,
  //   Icons.hourglass_empty,
  //   Icons.hourglass_full,
  //   Icons.http,
  //   Icons.https,
  //   Icons.image,
  //   Icons.image_aspect_ratio,
  //   Icons.import_contacts,
  //   Icons.import_export,
  //   Icons.important_devices,
  //   Icons.inbox,
  //   Icons.indeterminate_check_box,
  //   Icons.info,
  //   Icons.info_outline,
  //   Icons.input,
  //   Icons.insert_chart,
  //   Icons.insert_comment,
  //   Icons.insert_drive_file,
  //   Icons.insert_emoticon,
  //   Icons.insert_invitation,
  //   Icons.insert_link,
  //   Icons.insert_photo,
  //   Icons.invert_colors,
  //   Icons.invert_colors_off,
  //   Icons.iso,
  //   Icons.keyboard,
  //   Icons.keyboard_arrow_down,
  //   Icons.keyboard_arrow_left,
  //   Icons.keyboard_arrow_right,
  //   Icons.keyboard_arrow_up,
  //   Icons.keyboard_backspace,
  //   Icons.keyboard_capslock,
  //   Icons.keyboard_hide,
  //   Icons.keyboard_return,
  //   Icons.keyboard_tab,
  //   Icons.keyboard_voice,
  //   Icons.kitchen,
  //   Icons.label,
  //   Icons.label_important,
  //   Icons.label_outline,
  //   Icons.landscape,
  //   Icons.language,
  //   Icons.laptop,
  //   Icons.laptop_chromebook,
  //   Icons.laptop_mac,
  //   Icons.laptop_windows,
  //   Icons.last_page,
  //   Icons.launch,
  //   Icons.layers,
  //   Icons.layers_clear,
  //   Icons.leak_add,
  //   Icons.leak_remove,
  //   Icons.lens,
  //   Icons.library_add,
  //   Icons.library_books,
  //   Icons.library_music,
  //   Icons.lightbulb_outline,
  //   Icons.line_style,
  //   Icons.line_weight,
  //   Icons.linear_scale,
  //   Icons.link,
  //   Icons.link_off,
  //   Icons.linked_camera,
  //   Icons.list,
  //   Icons.live_help,
  //   Icons.live_tv,
  //   Icons.local_activity,
  //   Icons.local_airport,
  //   Icons.local_atm,
  //   Icons.local_bar,
  //   Icons.local_cafe,
  //   Icons.local_car_wash,
  //   Icons.local_convenience_store,
  //   Icons.local_dining,
  //   Icons.local_drink,
  //   Icons.local_florist,
  //   Icons.local_gas_station,
  //   Icons.local_grocery_store,
  //   Icons.local_hospital,
  //   Icons.local_hotel,
  //   Icons.local_laundry_service,
  //   Icons.local_library,
  //   Icons.local_mall,
  //   Icons.local_movies,
  //   Icons.local_offer,
  //   Icons.local_parking,
  //   Icons.local_pharmacy,
  //   Icons.local_phone,
  //   Icons.local_pizza,
  //   Icons.local_play,
  //   Icons.local_post_office,
  //   Icons.local_printshop,
  //   Icons.local_see,
  //   Icons.local_shipping,
  //   Icons.local_taxi,
  //   Icons.location_city,
  //   Icons.location_disabled,
  //   Icons.location_off,
  //   Icons.location_on,
  //   Icons.location_searching,
  //   Icons.lock,
  //   Icons.lock_open,
  //   Icons.lock_outline,
  //   Icons.looks,
  //   Icons.looks_3,
  //   Icons.looks_4,
  //   Icons.looks_5,
  //   Icons.looks_6,
  //   Icons.looks_one,
  //   Icons.looks_two,
  //   Icons.loop,
  //   Icons.loupe,
  //   Icons.low_priority,
  //   Icons.loyalty,
  //   Icons.mail,
  //   Icons.mail_outline,
  //   Icons.map,
  //   Icons.markunread,
  //   Icons.markunread_mailbox,
  //   Icons.maximize,
  //   Icons.memory,
  //   Icons.menu,
  //   Icons.merge_type,
  //   Icons.message,
  //   Icons.mic,
  //   Icons.mic_none,
  //   Icons.mic_off,
  //   Icons.minimize,
  //   Icons.missed_video_call,
  //   Icons.mms,
  //   Icons.mobile_screen_share,
  //   Icons.mode_comment,
  //   Icons.mode_edit,
  //   Icons.monetization_on,
  //   Icons.money_off,
  //   Icons.monochrome_photos,
  //   Icons.mood,
  //   Icons.mood_bad,
  //   Icons.more,
  //   Icons.more_horiz,
  //   Icons.more_vert,
  //   Icons.motorcycle,
  //   Icons.mouse,
  //   Icons.move_to_inbox,
  //   Icons.movie,
  //   Icons.movie_creation,
  //   Icons.movie_filter,
  //   Icons.multiline_chart,
  //   Icons.music_note,
  //   Icons.music_video,
  //   Icons.my_location,
  //   Icons.nature,
  //   Icons.nature_people,
  //   Icons.navigate_before,
  //   Icons.navigate_next,
  //   Icons.navigation,
  //   Icons.near_me,
  //   Icons.network_cell,
  //   Icons.network_check,
  //   Icons.network_locked,
  //   Icons.network_wifi,
  //   Icons.new_releases,
  //   Icons.next_week,
  //   Icons.nfc,
  //   Icons.no_encryption,
  //   Icons.no_sim,
  //   Icons.not_interested,
  //   Icons.not_listed_location,
  //   Icons.note,
  //   Icons.note_add,
  //   Icons.notification_important,
  //   Icons.notifications,
  //   Icons.notifications_active,
  //   Icons.notifications_none,
  //   Icons.notifications_off,
  //   Icons.notifications_paused,
  //   Icons.offline_bolt,
  //   Icons.offline_pin,
  //   Icons.ondemand_video,
  //   Icons.opacity,
  //   Icons.open_in_browser,
  //   Icons.open_in_new,
  //   Icons.open_with,
  //   Icons.outlined_flag,
  //   Icons.pages,
  //   Icons.pageview,
  //   Icons.palette,
  //   Icons.pan_tool,
  //   Icons.panorama,
  //   Icons.panorama_fish_eye,
  //   Icons.panorama_horizontal,
  //   Icons.panorama_vertical,
  //   Icons.panorama_wide_angle,
  //   Icons.party_mode,
  //   Icons.pause,
  //   Icons.pause_circle_filled,
  //   Icons.pause_circle_outline,
  //   Icons.payment,
  //   Icons.people,
  //   Icons.people_outline,
  //   Icons.perm_camera_mic,
  //   Icons.perm_contact_calendar,
  //   Icons.perm_data_setting,
  //   Icons.perm_device_information,
  //   Icons.perm_identity,
  //   Icons.perm_media,
  //   Icons.perm_phone_msg,
  //   Icons.perm_scan_wifi,
  //   Icons.person,
  //   Icons.person_add,
  //   Icons.person_outline,
  //   Icons.person_pin,
  //   Icons.person_pin_circle,
  //   Icons.personal_video,
  //   Icons.pets,
  //   Icons.phone,
  //   Icons.phone_android,
  //   Icons.phone_bluetooth_speaker,
  //   Icons.phone_forwarded,
  //   Icons.phone_in_talk,
  //   Icons.phone_iphone,
  //   Icons.phone_locked,
  //   Icons.phone_missed,
  //   Icons.phone_paused,
  //   Icons.phonelink,
  //   Icons.phonelink_erase,
  //   Icons.phonelink_lock,
  //   Icons.phonelink_off,
  //   Icons.phonelink_ring,
  //   Icons.phonelink_setup,
  //   Icons.photo,
  //   Icons.photo_album,
  //   Icons.photo_camera,
  //   Icons.photo_filter,
  //   Icons.photo_library,
  //   Icons.photo_size_select_actual,
  //   Icons.photo_size_select_large,
  //   Icons.photo_size_select_small,
  //   Icons.picture_as_pdf,
  //   Icons.picture_in_picture,
  //   Icons.picture_in_picture_alt,
  //   Icons.pie_chart,
  //   Icons.pie_chart_outline,
  //   Icons.pin_drop,
  //   Icons.place,
  //   Icons.play_arrow,
  //   Icons.play_circle_filled,
  //   Icons.play_circle_outline,
  //   Icons.play_for_work,
  //   Icons.playlist_add,
  //   Icons.playlist_add_check,
  //   Icons.playlist_play,
  //   Icons.plus_one,
  //   Icons.poll,
  //   Icons.polymer,
  //   Icons.pool,
  //   Icons.portable_wifi_off,
  //   Icons.portrait,
  //   Icons.power,
  //   Icons.power_input,
  //   Icons.power_settings_new,
  //   Icons.pregnant_woman,
  //   Icons.present_to_all,
  //   Icons.print,
  //   Icons.priority_high,
  //   Icons.public,
  //   Icons.publish,
  //   Icons.query_builder,
  //   Icons.question_answer,
  //   Icons.queue,
  //   Icons.queue_music,
  //   Icons.queue_play_next,
  //   Icons.radio,
  //   Icons.radio_button_checked,
  //   Icons.radio_button_unchecked,
  //   Icons.rate_review,
  //   Icons.receipt,
  //   Icons.recent_actors,
  //   Icons.record_voice_over,
  //   Icons.redeem,
  //   Icons.redo,
  //   Icons.refresh,
  //   Icons.remove,
  //   Icons.remove_circle,
  //   Icons.remove_circle_outline,
  //   Icons.remove_from_queue,
  //   Icons.remove_red_eye,
  //   Icons.remove_shopping_cart,
  //   Icons.reorder,
  //   Icons.repeat,
  //   Icons.repeat_one,
  //   Icons.replay,
  //   Icons.replay_10,
  //   Icons.replay_30,
  //   Icons.replay_5,
  //   Icons.reply,
  //   Icons.reply_all,
  //   Icons.report,
  //   Icons.report_off,
  //   Icons.report_problem,
  //   Icons.restaurant,
  //   Icons.restaurant_menu,
  //   Icons.restore,
  //   Icons.restore_from_trash,
  //   Icons.restore_page,
  //   Icons.ring_volume,
  //   Icons.room,
  //   Icons.room_service,
  //   Icons.rotate_90_degrees_ccw,
  //   Icons.rotate_left,
  //   Icons.rotate_right,
  //   Icons.rounded_corner,
  //   Icons.router,
  //   Icons.rowing,
  //   Icons.rss_feed,
  //   Icons.rv_hookup,
  //   Icons.satellite,
  //   Icons.save,
  //   Icons.save_alt,
  //   Icons.scanner,
  //   Icons.scatter_plot,
  //   Icons.schedule,
  //   Icons.school,
  //   Icons.score,
  //   Icons.screen_lock_landscape,
  //   Icons.screen_lock_portrait,
  //   Icons.screen_lock_rotation,
  //   Icons.screen_rotation,
  //   Icons.screen_share,
  //   Icons.sd_card,
  //   Icons.sd_storage,
  //   Icons.search,
  //   Icons.security,
  //   Icons.select_all,
  //   Icons.send,
  //   Icons.sentiment_dissatisfied,
  //   Icons.sentiment_neutral,
  //   Icons.sentiment_satisfied,
  //   Icons.sentiment_very_dissatisfied,
  //   Icons.sentiment_very_satisfied,
  //   Icons.settings,
  //   Icons.settings_applications,
  //   Icons.settings_backup_restore,
  //   Icons.settings_bluetooth,
  //   Icons.settings_brightness,
  //   Icons.settings_cell,
  //   Icons.settings_ethernet,
  //   Icons.settings_input_antenna,
  //   Icons.settings_input_component,
  //   Icons.settings_input_composite,
  //   Icons.settings_input_hdmi,
  //   Icons.settings_input_svideo,
  //   Icons.settings_overscan,
  //   Icons.settings_phone,
  //   Icons.settings_power,
  //   Icons.settings_remote,
  //   Icons.settings_system_daydream,
  //   Icons.settings_voice,
  //   Icons.share,
  //   Icons.shop,
  //   Icons.shop_two,
  //   Icons.shopping_basket,
  //   Icons.shopping_cart,
  //   Icons.short_text,
  //   Icons.show_chart,
  //   Icons.shuffle,
  //   Icons.shutter_speed,
  //   Icons.signal_cellular_4_bar,
  //   Icons.signal_cellular_connected_no_internet_4_bar,
  //   Icons.signal_cellular_no_sim,
  //   Icons.signal_cellular_null,
  //   Icons.signal_cellular_off,
  //   Icons.signal_wifi_4_bar,
  //   Icons.signal_wifi_4_bar_lock,
  //   Icons.signal_wifi_off,
  //   Icons.sim_card,
  //   Icons.sim_card_alert,
  //   Icons.skip_next,
  //   Icons.skip_previous,
  //   Icons.slideshow,
  //   Icons.slow_motion_video,
  //   Icons.smartphone,
  //   Icons.smoke_free,
  //   Icons.smoking_rooms,
  //   Icons.sms,
  //   Icons.sms_failed,
  //   Icons.snooze,
  //   Icons.sort,
  //   Icons.sort_by_alpha,
  //   Icons.spa,
  //   Icons.space_bar,
  //   Icons.speaker,
  //   Icons.speaker_group,
  //   Icons.speaker_notes,
  //   Icons.speaker_notes_off,
  //   Icons.speaker_phone,
  //   Icons.spellcheck,
  //   Icons.star,
  //   Icons.star_border,
  //   Icons.star_half,
  //   Icons.stars,
  //   Icons.stay_current_landscape,
  //   Icons.stay_current_portrait,
  //   Icons.stay_primary_landscape,
  //   Icons.stay_primary_portrait,
  //   Icons.stop,
  //   Icons.stop_screen_share,
  //   Icons.storage,
  //   Icons.store,
  //   Icons.store_mall_directory,
  //   Icons.straighten,
  //   Icons.streetview,
  //   Icons.strikethrough_s,
  //   Icons.style,
  //   Icons.subdirectory_arrow_left,
  //   Icons.subdirectory_arrow_right,
  //   Icons.subject,
  //   Icons.subscriptions,
  //   Icons.subtitles,
  //   Icons.subway,
  //   Icons.supervised_user_circle,
  //   Icons.supervisor_account,
  //   Icons.surround_sound,
  //   Icons.swap_calls,
  //   Icons.swap_horiz,
  //   Icons.swap_horizontal_circle,
  //   Icons.swap_vert,
  //   Icons.swap_vertical_circle,
  //   Icons.switch_camera,
  //   Icons.switch_video,
  //   Icons.sync,
  //   Icons.sync_disabled,
  //   Icons.sync_problem,
  //   Icons.system_update,
  //   Icons.system_update_alt,
  //   Icons.tab,
  //   Icons.tab_unselected,
  //   Icons.table_chart,
  //   Icons.tablet,
  //   Icons.tablet_android,
  //   Icons.tablet_mac,
  //   Icons.tag_faces,
  //   Icons.tap_and_play,
  //   Icons.terrain,
  //   Icons.text_fields,
  //   Icons.text_format,
  //   Icons.text_rotate_up,
  //   Icons.text_rotate_vertical,
  //   Icons.text_rotation_angledown,
  //   Icons.text_rotation_angleup,
  //   Icons.text_rotation_down,
  //   Icons.text_rotation_none,
  //   Icons.textsms,
  //   Icons.texture,
  //   Icons.theaters,
  //   Icons.thumb_down,
  //   Icons.thumb_up,
  //   Icons.thumbs_up_down,
  //   Icons.time_to_leave,
  //   Icons.timelapse,
  //   Icons.timeline,
  //   Icons.timer,
  //   Icons.timer_10,
  //   Icons.timer_3,
  //   Icons.timer_off,
  //   Icons.title,
  //   Icons.toc,
  //   Icons.today,
  //   Icons.toll,
  //   Icons.tonality,
  //   Icons.touch_app,
  //   Icons.toys,
  //   Icons.track_changes,
  //   Icons.traffic,
  //   Icons.train,
  //   Icons.tram,
  //   Icons.transfer_within_a_station,
  //   Icons.transform,
  //   Icons.transit_enterexit,
  //   Icons.translate,
  //   Icons.trending_down,
  //   Icons.trending_flat,
  //   Icons.trending_up,
  //   Icons.trip_origin,
  //   Icons.tune,
  //   Icons.turned_in,
  //   Icons.turned_in_not,
  //   Icons.tv,
  //   Icons.unarchive,
  //   Icons.undo,
  //   Icons.unfold_less,
  //   Icons.unfold_more,
  //   Icons.update,
  //   Icons.usb,
  //   Icons.verified_user,
  //   Icons.vertical_align_bottom,
  //   Icons.vertical_align_center,
  //   Icons.vertical_align_top,
  //   Icons.vibration,
  //   Icons.video_call,
  //   Icons.video_label,
  //   Icons.video_library,
  //   Icons.videocam,
  //   Icons.videocam_off,
  //   Icons.videogame_asset,
  //   Icons.view_agenda,
  //   Icons.view_array,
  //   Icons.view_carousel,
  //   Icons.view_column,
  //   Icons.view_comfy,
  //   Icons.view_compact,
  //   Icons.view_day,
  //   Icons.view_headline,
  //   Icons.view_list,
  //   Icons.view_module,
  //   Icons.view_quilt,
  //   Icons.view_stream,
  //   Icons.view_week,
  //   Icons.vignette,
  //   Icons.visibility,
  //   Icons.visibility_off,
  //   Icons.voice_chat,
  //   Icons.voicemail,
  //   Icons.volume_down,
  //   Icons.volume_mute,
  //   Icons.volume_off,
  //   Icons.volume_up,
  //   Icons.vpn_key,
  //   Icons.vpn_lock,
  //   Icons.wallpaper,
  //   Icons.warning,
  //   Icons.watch,
  //   Icons.watch_later,
  //   Icons.wb_auto,
  //   Icons.wb_cloudy,
  //   Icons.wb_incandescent,
  //   Icons.wb_iridescent,
  //   Icons.wb_sunny,
  //   Icons.wc,
  //   Icons.web,
  //   Icons.web_asset,
  //   Icons.weekend,
  //   Icons.whatshot,
  //   Icons.widgets,
  //   Icons.wifi,
  //   Icons.wifi_lock,
  //   Icons.wifi_tethering,
  //   Icons.work,
  //   Icons.wrap_text,
  //   Icons.youtube_searched_for,
  //   Icons.zoom_in,
  //   Icons.zoom_out,
  //   Icons.zoom_out_map,
  // ];
}
